
# MomoNail/docker-compose.yml

version: '3.8'

services:
  db:
    image: postgres:13                 # PostgreSQLのバージョン13を使用
    container_name: momonail_db
    environment:
      POSTGRES_DB: ${DB_NAME}          # .env ファイルから読み込む
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data # データ永続化
    ports:
      - "5432:5432" # 外部からDBに接続したい場合（開発中は不要な場合も）

  backend:
    build:
      context: ./backend               # backendディレクトリのDockerfileを使用
      dockerfile: Dockerfile
    container_name: momonail_backend
    command: python manage.py runserver 0.0.0.0:8000 # Django開発サーバーを起動
    volumes:
      - ./backend:/app                 # ホストのbackendディレクトリをコンテナの/appにマウント
    ports:
      - "8000:8000"                    # ホストの8000番ポートとコンテナの8000番ポートをマッピング
    depends_on:
      - db                             # dbサービスが起動するのを待つ
    environment:
      DATABASE_URL: postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME} # DB接続情報
      #ADMIN_LINE_CHANNEL_ACCESS_TOKEN: ${ADMIN_LINE_CHANNEL_ACCESS_TOKEN}
      #CUSTOMER_LINE_CHANNEL_ACCESS_TOKEN: ${CUSTOMER_LINE_CHANNEL_ACCESS_TOKEN}
      #LINE_USER_ID: ${LINE_USER_ID}
      #GOOGLE_CALENDAR_ID: ${GOOGLE_CALENDAR_ID}
      SECRET_KEY: '943ab9a14217a291afb02b8a42c77f3b'
      DEFAULT_FROM_EMAIL: 'nail.momo@nail_salon.com'
      EMAIL_HOST_USER: 'nail.reserve.momo@gmail.com'
      EMAIL_HOST_PASSWORD: 'ompqpdpjeejidhiu'
      GOOGLE_CALENDAR_ID: 'nail.reserve.momo@gmail.com'
      LINE_CHANNEL_ID: '2007607612'
      LINE_CHANNEL_SECRET: '2283496d397d979c7d772ed4e192bd64'
      LINE_REDIRECT_URI: 'http://localhost:5173/callback'
      FRONTEND_URL: 'http://localhost:5173'
      ADMIN_LINE_USER_ID: 'U65ee793d92ae926825335d2ed20dd52a'
      # 特殊文字を含むトークンも、この方法なら確実に読み込まれます
      ADMIN_LINE_CHANNEL_ACCESS_TOKEN: "sy0PmLbVkBQTpJliHMpjpXOPNFiXDSxMVBIw8YVczJlqmbbsacUb7Y2pVQ6JFnAFzZFUgEnY75goQSl8f7m7+7QSaFosggx9UtXwo99gj0l0GOIXK8xKFetFJ8blwYy/sZOncK27tbny+aCAyMydBQdB04t89/1O/w1cDnyilFU="
      CUSTOMER_LINE_CHANNEL_ACCESS_TOKEN: "6nmkjAc30xm9/jd8+Kka6JH7FE7Vt4AU5WxQmPmAAMNHZJIDjoVFkPNSzwXPwZmSnKwAw0aLvUKYbI6ZIgNJSMark5CpP564Ddb5+eivNwZnT2KqenbosYcbJlLwKmHqVJCmPMqp+CScs8zVr6RonwdB04t89/1O/w1cDnyilFU="
      
 
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args: # <<< ここを追加しました: ビルド時にVITE_API_BASE_URLを渡す
        VITE_API_BASE_URL: http://localhost:8000/ 
    container_name: momonail_frontend
#    command: npm run dev --host 0.0.0.0
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    depends_on:
      - backend
    environment:
      VITE_API_BASE_URL: http://localhost:8000

volumes:
  db_data: