# Generated by Django 4.2.22 on 2025-07-04 05:19

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_user_id', models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True)),
                ('line_registration_token', models.UUIDField(blank=True, default=uuid.uuid4, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='reservations.user')),
            ],
        ),
    ]
