# Generated by Django 4.2.22 on 2025-07-08 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='weeklydefaultschedule',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='weeklydefaultschedule',
            name='salon',
        ),
        migrations.DeleteModel(
            name='DateSchedule',
        ),
        migrations.DeleteModel(
            name='WeeklyDefaultSchedule',
        ),
    ]
