# Generated by Django 4.2.22 on 2025-07-08 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_alter_weeklydefaultschedule_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='furigana',
            field=models.CharField(blank=True, max_length=100, verbose_name='フリガナ'),
        ),
    ]
