# Generated by Django 4.2.22 on 2025-07-09 08:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_customer_furigana'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sender_type', models.CharField(choices=[('customer', '顧客'), ('admin', '管理者')], max_length=10, verbose_name='送信者')),
                ('message', models.TextField(blank=True, null=True, verbose_name='テキストメッセージ')),
                ('image_url', models.URLField(blank=True, max_length=2048, null=True, verbose_name='画像URL')),
                ('sent_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='送信日時')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_messages', to='reservations.customer')),
            ],
            options={
                'verbose_name': 'LINEメッセージ履歴',
                'verbose_name_plural': 'LINEメッセージ履歴',
                'ordering': ['sent_at'],
            },
        ),
    ]
