# Generated by Django 4.2.22 on 2025-07-16 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_linemessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linemessage',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='line_messages', to='reservations.customer'),
        ),
    ]
