# Generated by Django 4.2.22 on 2025-06-10 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0006_alter_reservation_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='dateschedule',
            name='is_holiday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='weeklydefaultschedule',
            name='is_holiday',
            field=models.BooleanField(default=False),
        ),
    ]
