# Generated by Django 4.2.22 on 2025-08-01 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0006_user_full_name_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='氏名'),
        ),
    ]
