# Generated by Django 4.2.22 on 2025-08-01 08:32

from django.db import migrations, models


def do_nothing(apps, schema_editor):
    """何もしない（no-op操作）"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0006_user_full_name_alter_user_username'),
    ]

    operations = [
        # full_nameフィールドは不要なため、何もしない
        migrations.RunPython(do_nothing, do_nothing),
    ]
