# Generated by Django 4.2.22 on 2025-08-10 08:59

from django.db import migrations
from django.db import connection


def remove_full_name_if_exists(apps, schema_editor):
    """full_nameカラムが存在する場合のみ削除する"""
    with connection.cursor() as cursor:
        # PostgreSQLでカラムの存在をチェック
        cursor.execute("""
            SELECT column_name 
            FROM information_schema.columns 
            WHERE table_name='reservations_userprofile' 
            AND column_name='full_name'
        """)
        
        if cursor.fetchone():
            # カラムが存在する場合のみ削除
            cursor.execute("ALTER TABLE reservations_userprofile DROP COLUMN full_name")


def reverse_remove_full_name(apps, schema_editor):
    """リバース操作：full_nameカラムを追加"""
    with connection.cursor() as cursor:
        cursor.execute("""
            ALTER TABLE reservations_userprofile 
            ADD COLUMN full_name VARCHAR(255) NULL
        """)


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0008_fix_userprofile_foreign_key'),
    ]

    operations = [
        migrations.RunPython(
            remove_full_name_if_exists,
            reverse_remove_full_name
        ),
    ]
