# Generated by Django 4.2.22 on 2025-08-09 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0008_fix_userprofile_foreign_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='full_name',
        ),
    ]
