# Generated by Django 4.2.22 on 2025-08-10 08:59

from django.db import migrations


def do_nothing(apps, schema_editor):
    """何もしない（no-op操作）"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0008_fix_userprofile_foreign_key'),
    ]

    operations = [
        # full_nameフィールドは0007で追加されていないため、削除も不要
        migrations.RunPython(do_nothing, do_nothing),
    ]
