# Generated by Django 4.2.22 on 2025-06-19 09:54

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0008_availabletimeslot'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='氏名')),
                ('email', models.EmailField(help_text='顧客を一意に識別するために使用します。', max_length=254, unique=True, verbose_name='メールアドレス')),
                ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='電話番号')),
                ('line_user_id', models.CharField(blank=True, db_index=True, help_text='LINEでの通知や連携に使用する一意のIDです。', max_length=255, null=True, unique=True, verbose_name='LINEユーザーID')),
                ('line_display_name', models.CharField(blank=True, help_text='LINEプロフィールの表示名です。', max_length=100, verbose_name='LINE表示名')),
                ('line_picture_url', models.URLField(blank=True, max_length=2048, verbose_name='LINEプロフィール画像URL')),
                ('notes', models.TextField(blank=True, help_text='顧客に関するメモなどを記載します。', verbose_name='備考')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='customer_email',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='customer_name',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='customer_phone',
        ),
        migrations.AlterField(
            model_name='reservation',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reservation_number',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.service'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('pending', '保留中'), ('confirmed', '確定済み'), ('cancelled', 'キャンセル済み')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='reservation',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='reservations.customer', verbose_name='顧客'),
        ),
    ]
