# Generated by Django 4.2.22 on 2025-06-19 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0009_customer_remove_reservation_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, help_text='顧客を一意に識別するために使用します。', max_length=254, null=True, verbose_name='メールアドレス'),
        ),
    ]
