# Generated by Django 4.2.22 on 2025-06-20 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0011_customer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, help_text='顧客を一意に識別するために使用します。', max_length=254, null=True, unique=True, verbose_name='メールアドレス'),
        ),
    ]
