# Generated by Django 4.2.22 on 2025-06-20 12:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0012_alter_customer_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='id',
        ),
        migrations.AlterField(
            model_name='customer',
            name='line_user_id',
            field=models.CharField(default=uuid.uuid4, help_text='LINEでの通知や連携に使用する一意のIDです。', max_length=255, primary_key=True, serialize=False, verbose_name='LINEユーザーID'),
        ),
    ]
