# Generated by Django 4.2.22 on 2025-06-24 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0013_remove_customer_id_alter_customer_line_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='user',
        ),
    ]
